spring.application.name=WishportAPI


#Puerto donde se encenderá el servidor (el camarero)
server.port=8080

#Conexión a la base de datos MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/wishport_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / Hibernate (Para que Spring entienda SQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configuración Jackson para fechas ISO UTC
spring.jackson.time-zone=UTC

